### ISSUE TITLE
[Port Manager] need to send down the correct neighbor info to Data Plane Manager

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor#343]
With the latest change from PR #301 , Data Plane Manager complains about:

2020-08-07 04:14:55.976  WARN 1 --- [nio-8080-exec-3] global                                   : portId: 722eede1-6c4b-42eb-8289-a077c754296b provided in neighbor but NOT in port_internal, skip for now, likely to be dpm client error
java.lang.NullPointerException
 at com.futurewei.alcor.dataplane.utils.GoalStateManager.lambda$transformNorthToSouth$1(GoalStateManager.java:267)
 at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
 at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
 at com.futurewei.alcor.dataplane.utils.GoalStateManager.lambda$transformNorthToSouth$2(GoalStateManager.java:176)

Expected:

DPM should be able to consume the input from port manager and then send down goal state message to alcor control agent on compute host for port provisioning

Actual:

DPM return error and not able to send down goal state message to alcor control agent on compute host for port provisioning

**Comment by xieus** [comment]
I believe this issue has been resolved in the current master. Can you confirm @haboy52581 @er1cthe0ne

**Comment by xieus** [comment]
I think this issue has been addressed a while ago. Close it for good.
