### ISSUE TITLE
[Data Plane Manager] shouldn't throw NullPointerException

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor#344]
DPM shouldn't throw NullPointerException even with bad input from its client. The exception should be caught and re-throw our own exception with error code and exception message pointing out what went wrong. Relevent error log below:

2020-08-07 04:14:55.976  WARN 1 --- [nio-8080-exec-3] global                                   : portId: 722eede1-6c4b-42eb-8289-a077c754296b provided in neighbor but NOT in port_internal, skip for now, likely to be dpm client error

java.lang.NullPointerException
 at com.futurewei.alcor.dataplane.utils.GoalStateManager.lambda$transformNorthToSouth$1(GoalStateManager.java:267)
 at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
 at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
 at com.futurewei.alcor.dataplane.utils.GoalStateManager.lambda$transformNorthToSouth$2(GoalStateManager.java:176)

**Comment by haboy52581** [comment]
fixed in pr345

**Comment by xieus** [comment]
This issue has been fixed in PR #345.
