### ISSUE TITLE
[Stress Test] Port deletion hit ~1% failure rate when Port Mgr under high load

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#370]
__Bug Description__

When RPS reaches 500, port deletion workflow appears to hit an IO error occasionally and the failure rate is about 1% (12 out of 1000 tests). Port creation workflow looks fine.  

__Client logs__

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rally/task/runner.py", line 72, in _run_scenario_once
    getattr(scenario_inst, method_name)(**scenario_kwargs)
  File "/usr/lib/python2.7/dist-packages/rally/plugins/openstack/scenarios/alcor/network.py", line 343, in run
    port = self._create_port(network, port_create_args)
  File "/usr/lib/python2.7/dist-packages/rally/task/atomic.py", line 84, in func_atomic_actions
    f = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rally/plugins/openstack/scenarios/alcor/utils.py", line 249, in _create_port
    return self.clients("alcor").create_port({"port": port_create_args})
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 806, in create_port
    return self.post(self.ports_path, body=body)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 294, in do_request
    self._handle_fault_response(status_code, replybody, resp)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 269, in _handle_fault_response
    exception_handler_v20(status_code, error_body)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 93, in exception_handler_v20
    request_ids=request_ids)
InternalServerError: Task java.util.concurrent.CompletableFuture$AsyncSupply@53039f85 rejected from java.util.concurrent.ThreadPoolExecutor@3bab433b[Running, pool size = 20, active threads = 20, queued tasks = 1024, completed tasks = 82882]
```

__Port Mgr logs__
```
2020-08-31 18:54:23.552 DEBUG 1 --- [io-8080-exec-95] o.a.coyote.http11.Http11InputBuffer      : Received [DELETE /project/f8b4d1402a86467f88550c565f63dd22/ports/4d9a9469-7e9d-4e40-9ffb-b8f67df56ea5 HTTP/1.1
Accept: application/json
--
java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1231) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1141) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:755) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:356) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.33.jar!/:9.0.33]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by xieus** [comment]
@chenpiaoping Piaoping, please take a look at this issue when you get a chance.

**Comment by chenpiaoping** [comment]
@xieus InternalServerError: Task java.util.concurrent.CompletableFuture$AsyncSupply@53039f85 rejected from java.util.concurrent.ThreadPoolExecutor@3bab433b[Running, pool size = 20, active threads = 20, queued tasks = 1024, completed tasks = 82882]
From this log, queued tasks is 1024. It seems that PM can no longer handle so many requests, and fillReadBuffer() throws a java.io.EOFException exception, indicating that EOF has been read when reading the data. It may be that the session has been closed, due to timeout or other reasons. Did you call PM's API directly or through API gateway? Could you modify the request timeout and try again?  Spring.mvc.async.request-timeout=30000 (representing 30 seconds)

**Comment by chenpiaoping** [comment]
Currently, restclient is implemented based on restTemplate, and restTemplate is synchronous, so threads will block on rest requests, and the performance is poor compared to asynchronous rest. In the future, we can use asynchronous rest, to estimate that the performance will be improved.

**Comment by xieus** [comment]
> Did you call PM's API directly or through API gateway? Could you modify the request timeout and try again? Spring.mvc.async.request-timeout=30000 (representing 30 seconds)

This is E2E testing result therefore every call went through API GW.

Sure. Do you mean add the following configuration in application.properties in PM? 
```
Spring.mvc.async.request-timeout=30000
```

**Comment by chenpiaoping** [comment]
Both PM and API gateway, to see if this configuration is helpful to this problem.

**Comment by xieus** [comment]
> Currently, restclient is implemented based on restTemplate, and restTemplate is synchronous, so threads will block on rest requests, and the performance is poor compared to asynchronous rest. In the future, we can use asynchronous rest, to estimate that the performance will be improved.

That is a good idea. Let us see whether increasing timeout helps or not.

Wait, one second, the timeout configuration Spring.mvc.async.request-timeout is an async configuration. Will it help if PM is using a sync rest client as of now?

**Comment by chenpiaoping** [comment]
This should be a configuration of spring MVC, which has nothing to do with our rest.

**Comment by xieus** [comment]
@chenpiaoping Tried to extend the timeout in both API GW and Port Mgr as suggested. still hit 1-2% failure rate.

**Comment by xieus** [comment]
@chenpiaoping Pls check the details in PR #401, which should fix this issue.
