### ISSUE TITLE
[Stress Test] VPC creation/update hits ~1% failure rate when VPC manager under high load

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#371]
__ Bug Description__

When rps=500, VPC manager throws com.futurewei.alcor.vpcmanager.exception.NetworkKeyAllocNotFoundException in about 1% of all test cases (<10 among 1000 tests). 

__Client logs__
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rally/task/runner.py", line 72, in _run_scenario_once
    getattr(scenario_inst, method_name)(**scenario_kwargs)
  File "/usr/lib/python2.7/dist-packages/rally/plugins/openstack/scenarios/alcor/network.py", line 44, in run
    self._create_network(network_create_args or {})
  File "/usr/lib/python2.7/dist-packages/rally/task/atomic.py", line 84, in func_atomic_actions
    f = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rally/plugins/openstack/scenarios/alcor/utils.py", line 84, in _create_network
    {"network": network_create_args})
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 851, in create_network
    return self.post(self.networks_path, body=body)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 294, in do_request
    self._handle_fault_response(status_code, replybody, resp)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 269, in _handle_fault_response
    exception_handler_v20(status_code, error_body)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 93, in exception_handler_v20
    request_ids=request_ids)
NotFound: Key allocation is not found
```

__VPC Mgr logs__
```
2020-09-01 23:18:55.224 DEBUG 1 --- [o-8080-exec-201] o.a.c.authenticator.AuthenticatorBase    : Security checking request PUT /project/a8fbb9b9173b4ffda53087d84e10432a/vpcs/00dffb6a-8a90-497f-b13d-5d77973d21dd
2020-09-01 23:18:55.224 DEBUG 1 --- [o-8080-exec-201] org.apache.catalina.realm.RealmBase      :   No applicable constraints defined
2020-09-01 23:18:55.224 DEBUG 1 --- [o-8080-exec-201] o.a.c.authenticator.AuthenticatorBase    :  Not subject to any constraint
2020-09-01 23:18:55.224 DEBUG 1 --- [o-8080-exec-201] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
2020-09-01 23:18:55.224 DEBUG 1 --- [o-8080-exec-201] o.s.web.servlet.DispatcherServlet        : PUT "/project/a8fbb9b9173b4ffda53087d84e10432a/vpcs/00dffb6a-8a90-497f-b13d-5d77973d21dd", parameters={}
2020-09-01 23:18:55.224 DEBUG 1 --- [o-8080-exec-201] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to public com.futurewei.alcor.web.entity.vpc.VpcWebJson com.futurewei.alcor.vpcmanager.controller.VpcController.updateVpcStateByVpcId(java.lang.String,java.lang.String,com.futurewei.alcor.web.entity.vpc.VpcWebRequestJson) throws java.lang.Exception
2020-09-01 23:18:55.224 DEBUG 1 --- [o-8080-exec-201] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5bf990c8:org.apache.tomcat.util.net.NioChannel@7c4d5352:java.nio.channels.SocketChannel[connected local=/172.16.206.215:8080 remote=/172.16.19.182:34580]], Read from buffer: [0]
2020-09-01 23:18:55.224 DEBUG 1 --- [o-8080-exec-201] org.apache.tomcat.util.net.NioEndpoint   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5bf990c8:org.apache.tomcat.util.net.NioChannel@7c4d5352:java.nio.channels.SocketChannel[connected local=/172.16.206.215:8080 remote=/172.16.19.182:34580]], Read direct from socket: [75]
2020-09-01 23:18:55.224 DEBUG 1 --- [o-8080-exec-201] m.m.a.RequestResponseBodyMethodProcessor : Read "application/json;charset=UTF-8" to [VpcWebRequestJson(network=VpcWebRequest(cidr=null, routeEntities=null, adminStateUp=false, dnsDomain (truncated)...]
2020-09-01 23:18:55.224 DEBUG 1 --- [o-8080-exec-201] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.controller.VpcController.updateVpcStateByVpcId()...
2020-09-01 23:18:55.225 DEBUG 1 --- [o-8080-exec-201] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.service.Impl.VpcDatabaseServiceImpl.getByVpcId()...
2020-09-01 23:18:55.225 DEBUG 1 --- [o-8080-exec-201] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.dao.VpcRepository.findItem()...
2020-09-01 23:18:55.225  INFO 1 --- [o-8080-exec-298] c.f.alcor.common.stats.StatisticsAspect  : com.futurewei.alcor.vpcmanager.dao.VpcRepository.addItem() startTime: 1380542186818327ns, endTime: 1380542189997429ns, duration: 3ms
2020-09-01 23:18:55.225  INFO 1 --- [o-8080-exec-298] c.f.alcor.common.stats.StatisticsAspect  : com.futurewei.alcor.vpcmanager.service.Impl.VpcDatabaseServiceImpl.addVpc() startTime: 1380542186805142ns, endTime: 1380542190028143ns, duration: 3ms
2020-09-01 23:18:55.225 DEBUG 1 --- [o-8080-exec-298] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.service.Impl.VpcDatabaseServiceImpl.getByVpcId()...
2020-09-01 23:18:55.225 DEBUG 1 --- [o-8080-exec-298] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.dao.VpcRepository.findItem()...
2020-09-01 23:18:55.225 DEBUG 1 --- [o-8080-exec-345] .w.s.m.a.ResponseStatusExceptionResolver : Resolved [com.futurewei.alcor.vpcmanager.exception.NetworkKeyAllocNotFoundException]
2020-09-01 23:18:55.225 DEBUG 1 --- [o-8080-exec-345] o.s.web.servlet.DispatcherServlet        : Completed 404 NOT_FOUND
```

**Comment by xieus** [comment]
Debugged with @kevin-zhonghao and identified the issue when we tried to cleanup resource at the time of addVxlanEntity. 

https://github.com/futurewei-cloud/alcor/blob/65b8c53c05e177cd2da526cc230f04b9e1869516/services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/SegmentServiceImpl.java#L159

Next step is to replace releaseVxlanKey with tryReleaseVxlanKey, which doesn't throw exception if the key doesn't exist, and further debug the root cause.

**Comment by xieus** [comment]
Debugged with @kevin-zhonghao and @cj-chung and found the root cause.

__Root cause__
When customer create a VPC, control plane automatically allocates a VNI for the VPC. The problem is that the VNI range (VxLan range in this case) is created "on the fly" - the range isn't created until the customer allocates some VNI from the range. The logics doesn't sustain well when the customer load is very high at the time of control plane launch. 

__Proposed fix__
In PR #371, there will be a new API which allows admin to pre-create VNI ranges at control plane launch time.  

__VPC Mgr Logs__
```
2020-09-03 23:51:50.309 DEBUG 1 --- [o-8080-exec-230] o.s.web.client.RestTemplate              : HTTP POST http://routemanager-service.default.svc.cluster.local:9003/vpcs/083be1ba-4260-4ae9-bfb4-327a5276bbb0/routes
2020-09-03 23:51:50.309 DEBUG 1 --- [o-8080-exec-230] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
2020-09-03 23:51:50.309 DEBUG 1 --- [o-8080-exec-230] o.s.web.client.RestTemplate              : Writing [VpcWebJson(network=VpcEntity(cidr=null, routeEntities=null, adminStateUp=false, dnsDomain=null, mtu=1450, portSecurityEnabled=true, networkType=null, physicalNetwork=null, segmentationId=null, routerExternal=false, segments=null, shared=false, vlanTransparent=false, isDefault=false, availabilityZoneHints=null, availabilityZones=[Nova], qosPolicyId=null, revisionNumber=1, status=ACTIVE, tags=[], created_at=2020-09-03 23:51:50, updated_at=2020-09-03 23:51:50, ipv4AddressScope=null, ipv6AddressScope=null, l2Adjacency=null, subnets=null))] with org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
2020-09-03 23:51:50.310 DEBUG 1 --- [o-8080-exec-230] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@4c4a3ea87 pairs: {POST /vpcs/083be1ba-4260-4ae9-bfb4-327a5276bbb0/routes HTTP/1.1: null}{Accept: application/json, application/*+json}{Content-Type: application/json;charset=UTF-8}{User-Agent: Java/11.0.5}{Host: routemanager-service.default.svc.cluster.local:9003}{Connection: keep-alive}{Content-Length: 809}
2020-09-03 23:51:50.333 DEBUG 1 --- [o-8080-exec-230] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@76b36676 pairs: {null: HTTP/1.1 201}{Content-Type: application/json}{Transfer-Encoding: chunked}{Date: Thu, 03 Sep 2020 23:51:47 GMT}{Keep-Alive: timeout=60}{Connection: keep-alive}
2020-09-03 23:51:50.333 DEBUG 1 --- [o-8080-exec-230] o.s.web.client.RestTemplate              : Response 201 CREATED
2020-09-03 23:51:50.333 DEBUG 1 --- [o-8080-exec-230] o.s.web.client.RestTemplate              : Reading to [com.futurewei.alcor.web.entity.route.RouteWebJson]
2020-09-03 23:51:50.333  INFO 1 --- [o-8080-exec-230] c.f.alcor.common.stats.StatisticsAspect  : com.futurewei.alcor.vpcmanager.service.Impl.VpcServiceImpl.getRoute() startTime: 805984270116772ns, endTime: 805984294773475ns, duration: 24ms
2020-09-03 23:51:50.333 DEBUG 1 --- [o-8080-exec-230] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.service.Impl.VpcServiceImpl.allocateSegmentForNetwork()...
2020-09-03 23:51:50.333 DEBUG 1 --- [o-8080-exec-230] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.service.Impl.SegmentServiceImpl.addVxlanEntity()...
2020-09-03 23:51:50.333 DEBUG 1 --- [o-8080-exec-230] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.dao.VxlanRangeRepository.findItem()...
2020-09-03 23:51:50.335  INFO 1 --- [o-8080-exec-230] c.f.alcor.common.stats.StatisticsAspect  : com.futurewei.alcor.vpcmanager.dao.VxlanRangeRepository.findItem() startTime: 805984294942749ns, endTime: 805984296689145ns, duration: 1ms
2020-09-03 23:51:50.335 DEBUG 1 --- [o-8080-exec-230] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.dao.VxlanRangeRepository.createRange()...
2020-09-03 23:51:52.013  WARN 1 --- [o-8080-exec-230] c.f.a.v.dao.VxlanRangeRepository         : Create network range failed: Network Range already exists
2020-09-03 23:51:52.014 DEBUG 1 --- [o-8080-exec-230] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.dao.VxlanRepository.deleteItem()...
2020-09-03 23:51:52.014  INFO 1 --- [o-8080-exec-230] global                                   : Delete Vxlan, Vxlan Id:8ce8b93d-12a3-44ad-a6f8-6a1712835fbc
2020-09-03 23:51:52.019  INFO 1 --- [o-8080-exec-230] c.f.alcor.common.stats.StatisticsAspect  : com.futurewei.alcor.vpcmanager.dao.VxlanRepository.deleteItem() startTime: 805985975347395ns, endTime: 805985980285682ns, duration: 4ms
2020-09-03 23:51:52.019 DEBUG 1 --- [o-8080-exec-230] c.f.alcor.common.stats.StatisticsAspect  : Calculating duration of com.futurewei.alcor.vpcmanager.dao.VxlanRangeRepository.releaseVxlanKey()...
2020-09-03 23:51:52.741  INFO 1 --- [o-8080-exec-230] c.f.alcor.common.stats.StatisticsAspect  : com.futurewei.alcor.vpcmanager.dao.VxlanRangeRepository.releaseVxlanKey() startTime: 805985980373100ns, endTime: 805986702212540ns, duration: 721ms
2020-09-03 23:51:52.741  INFO 1 --- [o-8080-exec-230] c.f.a.v.service.Impl.SegmentServiceImpl  : Allocate vxlan key or db operation failed, key: null
2020-09-03 23:51:52.741 DEBUG 1 --- [o-8080-exec-230] .w.s.m.a.ResponseStatusExceptionResolver : Resolved [com.futurewei.alcor.vpcmanager.exception.NetworkRangeExistException]
2020-09-03 23:51:52.741 DEBUG 1 --- [o-8080-exec-230] o.s.web.servlet.DispatcherServlet        : Completed 409 CONFLICT
```
