### ISSUE TITLE
[Stress Test] AlcorNetworks.create_and_list_networks test case experiences connection timeout issues at high load

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#372]
__Bug Description__
Among 1000 iterations of create_and_list_networks, test clients received ConnectTimeout issues in ~80 out of 1000 iterations. This could be caused by API GW by observing high CPU usage, or a test client issue. 

[Observation 1]:  The error message doesn't show up at all in the first set of tests suites (of same tests, same number of iterations) but only show up in the second set.. 

More investigation is required.

__Client logs__
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rally/task/runner.py", line 72, in _run_scenario_once
    getattr(scenario_inst, method_name)(**scenario_kwargs)
  File "/usr/lib/python2.7/dist-packages/rally/plugins/openstack/scenarios/alcor/network.py", line 44, in run
    self._create_network(network_create_args or {})
  File "/usr/lib/python2.7/dist-packages/rally/task/atomic.py", line 84, in func_atomic_actions
    f = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rally/plugins/openstack/scenarios/alcor/utils.py", line 84, in _create_network
    {"network": network_create_args})
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 851, in create_network
    return self.post(self.networks_path, body=body)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/alcorclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1011, in _send_request
    raise exceptions.ConnectTimeout(msg)
ConnectTimeout: Request to http://10.213.43.170:30004/v2.0/networks timed out
```

**Comment by xieus** [comment]
@cj-chung I believe this issue has gone for some time. Could you please confirm?

**Comment by xieus** [comment]
The second test appears to use admin token so that we can specify network type. The admin operations usually don't come in high frequency nor in high load. 

Lower the priority to P2.
