### ISSUE TITLE
[Deployment] KeyStone Scale-out to mitigate Java Socket exception

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#419]
__Client Log__

Traceback (most recent call last):
```
  File "/usr/lib/python2.7/dist-packages/rally/task/runner.py", line 72, in _run_scenario_once
    getattr(scenario_inst, method_name)(**scenario_kwargs)
  File "/usr/lib/python2.7/dist-packages/rally/plugins/openstack/scenarios/neutron/network.py", line 95, in run
    network = self._create_network(network_create_args or {})
  File "/usr/lib/python2.7/dist-packages/rally/task/atomic.py", line 84, in func_atomic_actions
    f = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rally/plugins/openstack/scenarios/neutron/utils.py", line 84, in _create_network
    {"network": network_create_args})
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 851, in create_network
    return self.post(self.networks_path, body=body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 294, in do_request
    self._handle_fault_response(status_code, replybody, resp)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 269, in _handle_fault_response
    exception_handler_v20(status_code, error_body)
  File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 93, in exception_handler_v20
    request_ids=request_ids)
InternalServerError: I/O error on GET request for "http://192.168.10.10:5000/v3/auth/tokens": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server
```

**Comment by cj-chung** [comment]
This issue is caused by the connection limitation in Keystone's Nginx and uWSGI service. To extend the number of  connection for Keystone's container, we need to do several steps as follows:
1) Login to keystone's container
2) check net.core.somaxconn by `cat /proc/sys/net/core/somaxconn`, the default value is 128
3) extend somaxconn by `sysctl -w net.core.somaxconn=2048` 
4) extend Nginx's workers and connections by modifying /etc/nginx/nginx.conf
```
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log
pid /var/run/nginx.pid;
worker_rlimit_nofile 65535;
events {
     worker_connections 65535;
}
```
5) extend workers and number of service listen in uWSGI by modifying /etc/uwsgi/keystone-uwsgi-public.ini
```
workers = 24
listen = 65535
```
6) restart keystone and nginx service
```
systemctl daemon-reload
service nginx restart
```

**Comment by xieus** [comment]
We verified the fix through a new round of Rally test. Close the issue.
