### ISSUE TITLE
[GM] unregisterVPC in GM got 500 internalserver error

### ISSUE THREAD

**Issue by yanmo96** [futurewei-cloud/alcor#652]
When run rally create_delete_networks.json will have the following error from Alcor k8s gatewaymanager:

```
2021-06-28 18:26:46.690 DEBUG 1 --- [nio-8080-exec-5] o.s.web.servlet.DispatcherServlet        : DELETE "/project/840ae0e56e864be1937fd6e179ac6265/gatewayinfo/448108d2-3156-4039-bcb9-115eee45b972", parameters={}
2021-06-28 18:26:46.691 DEBUG 1 --- [nio-8080-exec-4] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to com.futurewei.alcor.gatewaymanager.controller.GatewayController#deleteGatewayInfoForZeta(String, String)
2021-06-28 18:26:46.691 DEBUG 1 --- [nio-8080-exec-5] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to com.futurewei.alcor.gatewaymanager.controller.GatewayController#deleteGatewayInfoForZeta(String, String)
2021-06-28 18:26:46.732  WARN 1 --- [nio-8080-exec-5] global                                   : IgniteTransaction commit error:You can commit transaction only from the thread it was started
2021-06-28 18:26:46.737 DEBUG 1 --- [nio-8080-exec-5] o.s.web.servlet.DispatcherServlet        : Failed to complete request: com.futurewei.alcor.common.db.CacheException: IgniteTransaction commit error:You can commit transaction only from the thread it was started
2021-06-28 18:26:46.738 ERROR 1 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.futurewei.alcor.common.db.CacheException: IgniteTransaction commit error:You can commit transaction only from the thread it was started] with root cause
com.futurewei.alcor.common.db.CacheException: IgniteTransaction commit error:You can commit transaction only from the thread it was started
        at com.futurewei.alcor.common.db.ignite.IgniteClientTransaction.commit(IgniteClientTransaction.java:62) ~[common-0.1.0-SNAPSHOT.jar!/:0.1.0-SNAPSHOT]
        at com.futurewei.alcor.gatewaymanager.dao.GatewayRepository.deleteGatewayInfoForZeta(GatewayRepository.java:95) ~[classes!/:0.1.0-SNAPSHOT]
        at com.futurewei.alcor.gatewaymanager.dao.GatewayRepository$$FastClassBySpringCGLIB$$273c29c3.invoke(<generated>) ~[classes!/:0.1.0-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at com.futurewei.alcor.gatewaymanager.dao.GatewayRepository$$EnhancerBySpringCGLIB$$e073bea6.deleteGatewayInfoForZeta(<generated>) ~[classes!/:0.1.0-SNAPSHOT]
        at com.futurewei.alcor.gatewaymanager.service.GatewayService.deleteGatewayInfoForZeta(GatewayService.java:127) ~[classes!/:0.1.0-SNAPSHOT]
        at com.futurewei.alcor.gatewaymanager.controller.GatewayController.deleteGatewayInfoForZeta(GatewayController.java:86) ~[classes!/:0.1.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
```

**Comment by cj-chung** [comment]
This is caused by the function `deleteGatewayInfoForZeta`. The function didn't check the `zetaGatewayEnabled` flag.
Need to add 1 line of code `if (!zetaGatewayEnabled) return;` in the `deleteGatewayInfoForZeta` as follow:

```
    public void deleteGatewayInfoForZeta(String projectId, String vpcId) throws Exception {
        //TODO check whether the project type is zeta by projectId

        if (!zetaGatewayEnabled) return;

        Map<String, Object[]> queryParams = new HashMap<>();
        queryParams.put("resourceId", new String[]{vpcId});
        Map<String, GWAttachment> attachmentsMap = gwAttachmentRepository.findAllItems(queryParams);
        gatewayRepository.deleteGatewayInfoForZeta(attachmentsMap);
        ...
    }
```
